# Site settings
title: AcroBuddhas
email: acrobuddhas@gmail.com
description: Ryan and Miranda are an acrobatic yoga duo based in Toronto, Ontario, Canada.
Together, they are on a mission to spread their love for a healthy and uplifted lifestyle. Their philosophy in life is to follow your bliss and inspire others to do the same.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://acrobuddhas.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
