# Site settings
title: AcroBuddhas
email: acrobuddhas@gmail.com
description: Ryan and Miranda are an acrobatic yoga duo based in Toronto, Ontario, Canada.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://acrobuddhas.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
