# Site settings
title: AcroBuddhas
email: your-email@domain.com
description: AcroBuddhas
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://acrobuddhas.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
